;--------ACCENTS--------
(define-prefix-command 'stress-map)
(add-hook 'LaTeX-mode-hook (lambda () (global-set-key (kbd "#") 'stress-map)))
(add-hook 'text-mode-hook  (lambda () (global-set-key (kbd "#") 'stress-map)))
(define-key stress-map (kbd "a") '(lambda () (interactive) (insert "à")))
(define-key stress-map (kbd "e") '(lambda () (interactive) (insert "è")))
(define-key stress-map (kbd "i") '(lambda () (interactive) (insert "ì")))
(define-key stress-map (kbd "o") '(lambda () (interactive) (insert "ò")))
(define-key stress-map (kbd "u") '(lambda () (interactive) (insert "ù")))
(define-key stress-map (kbd "y") '(lambda () (interactive) (insert "ỳ")))
(define-key stress-map (kbd "' a") '(lambda () (interactive) (insert "á")))
(define-key stress-map (kbd "' e") '(lambda () (interactive) (insert "é")))
(define-key stress-map (kbd "' i") '(lambda () (interactive) (insert "í")))
(define-key stress-map (kbd "' o") '(lambda () (interactive) (insert "ó")))
(define-key stress-map (kbd "' u") '(lambda () (interactive) (insert "ú")))
(define-key stress-map (kbd "' y") '(lambda () (interactive) (insert "ý")))
(define-key stress-map (kbd "A") '(lambda () (interactive) (insert "À")))
(define-key stress-map (kbd "E") '(lambda () (interactive) (insert "È")))
(define-key stress-map (kbd "I") '(lambda () (interactive) (insert "Ì")))
(define-key stress-map (kbd "O") '(lambda () (interactive) (insert "Ò")))
(define-key stress-map (kbd "U") '(lambda () (interactive) (insert "Ù")))
(define-key stress-map (kbd "Y") '(lambda () (interactive) (insert "Ỳ")))
(define-key stress-map (kbd "' A") '(lambda () (interactive) (insert "Á")))
(define-key stress-map (kbd "' E") '(lambda () (interactive) (insert "É")))
(define-key stress-map (kbd "' I") '(lambda () (interactive) (insert "Í")))
(define-key stress-map (kbd "' O") '(lambda () (interactive) (insert "Ó")))
(define-key stress-map (kbd "' U") '(lambda () (interactive) (insert "Ú")))
(define-key stress-map (kbd "' Y") '(lambda () (interactive) (insert "Ý")))
