(global-set-key (kbd "C-c j i") '(lambda () (interactive) (insert "~/.my_spacemacs.d/init/others.el")))
(global-set-key (kbd "C-c j o") '(lambda () (interactive) (insert "~/.my_spacemacs.d/init/org.el")))
(global-set-key (kbd "C-c j p") '(lambda () (interactive) (insert "~/programming/_projects/pdf-something")))
(global-set-key (kbd "C-c j e") '(lambda () (interactive) (insert "~/programming/macOS/easyLyceum")))
(global-set-key (kbd "C-c j y") '(lambda () (interactive) (insert "~/.my_spacemacs.d/snippets/")))
;; (global-set-key (kbd "C-c j t") '(lambda () (interactive) (insert "~/bioinformatics/thesis/R/TargetScanTools")))
(global-set-key (kbd "C-c j l") '(lambda () (interactive) (insert "~/bioinformatics/thesis_latex_only/")))
;; (global-set-key (kbd "C-c j c") '(lambda () (interactive) (insert "~/bioinformatics/thesis/R/TargetScanTools")))
(global-set-key (kbd "C-c j m") '(lambda () (interactive) (insert "~/bioinformatics/github/mirna_target_prediction")))
(global-set-key (kbd "C-c j d") '(lambda () (interactive) (insert "~/programming/python/sd/src/")))
(global-set-key (kbd "C-c j f") '(lambda () (interactive) (insert "~/free_time")))
